apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: profile-service-secrets
  # ... other metadata
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/461501268972/secrets/profile-service-encryption-key/versions/latest"
        path: "encryption-key"
      - resourceName: "projects/461501268972/secrets/profile-service-db-password/versions/latest"
        path: "db-password"
  secretObjects:
    - secretName: profile-service-secrets
      type: Opaque
      data:
        - objectName: "encryption-key"
          key: "encryption-key"
        - objectName: "db-password"
          key: "db-password"