apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: utility-service-secrets
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/461501268972/secrets/utility-service-google-maps-api-key/versions/latest"
        path: "google-maps-api-key"
  secretObjects:
    - secretName: utility-service-secrets
      type: Opaque
      data:
        - objectName: "google-maps-api-key"
          key: "google-maps-api-key"