# csi-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secrets-store-csi-driver-gke-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "delete","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secrets-store-csi-driver-gke-binding
subjects:
  - kind: ServiceAccount
    name: secrets-store-csi-driver-gke
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: secrets-store-csi-driver-gke-role
  apiGroup: rbac.authorization.k8s.io