apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat-gcp-role
rules:
- apiGroups: [""]
  resources:
  - nodes
  - namespaces
  - pods
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat-gcp-binding
subjects:
- kind: ServiceAccount
  name: filebeat-ksa
  namespace: default
roleRef:
  kind: ClusterRole
  name: filebeat-gcp-role
  apiGroup: rbac.authorization.k8s.io