apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: order-service-secrets
  # ... other metadata
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/461501268972/secrets/order-service-order-database-password/versions/latest"
        path: "order-database-password"
      - resourceName: "projects/461501268972/secrets/order-service-cart-database-password/versions/latest"
        path: "cart-database-password"
  secretObjects:
    - secretName: order-service-secrets
      type: Opaque
      data:
        - objectName: "order-database-password"
          key: "order-database-password"
        - objectName: "cart-database-password"
          key: "cart-database-password"