apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.10.0
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch:9200"
            - name: SERVER_SSL_ENABLED
              value: "false"
            - name: SERVER_HOST
              value: "0.0.0.0"
            - name: SERVER_PUBLICBASEURL
              value: "http://kibana.shopsmartsg.com"
            - name: XPACK_SECURITY_ENABLED
              value: "true"
            - name: ELASTICSEARCH_USERNAME
              value: "kibana_system"
            - name: ELASTICSEARCH_PASSWORD
              value: "NewPassword123"
            - name: SERVER_HEALTHCHECK_ALLOWANONYMOUS
              value: "true"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /api/status
              port: 5601
              scheme: HTTP
              httpHeaders:
                - name: Authorization
                  value: "Basic ZWxhc3RpYzpKQ3FNUmtKZVhPSDhOTFZLQ1ljZg=="
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/status
              port: 5601
              scheme: HTTP
              httpHeaders:
                - name: Authorization
                  value: "Basic ZWxhc3RpYzpKQ3FNUmtKZVhPSDhOTFZLQ1ljZg=="
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /api/status
              port: 5601
              scheme: HTTP
              httpHeaders:
                - name: Authorization
                  value: "Basic ZWxhc3RpYzpKQ3FNUmtKZVhPSDhOTFZLQ1ljZg=="
            failureThreshold: 30
            periodSeconds: 10
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "purpose"
                    operator: In
                    values:
                      - "elk"
                  - key: "set"
                    operator: In
                    values:
                      - "ss-elk"
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  annotations:
    cloud.google.com/backend-config: '{"default": "kibana-backend-config"}'
spec:
  selector:
    app: kibana
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
  type: ClusterIP