apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
data:
  kibana.yml: |
    server.host: "0.0.0.0"
    server.ssl.enabled: true
    server.ssl.certificate: "/usr/share/kibana/config/certs/tls.crt"
    server.ssl.key: "/usr/share/kibana/config/certs/tls.key"
    
    elasticsearch.hosts: "http://elasticsearch:9200"
    elasticsearch.username: "kibana_system"
    elasticsearch.password: "${ELASTICSEARCH_PASSWORD}"
    
    xpack.security.enabled: true
    xpack.security.encryptionKey: "${XPACK_SECURITY_ENCRYPTIONKEY}"
    
    # OIDC configuration with explicit SSL settings
    xpack.security.authc.providers:
      oidc.google:
        order: 1
        realm: google
        description: "Log in with Google"
        icon: "googleLogo"
      basic.basic1:
        order: 0
    
    
    
    # Cookie settings
    xpack.security.secureCookies: true
    xpack.security.cookieName: "sid"
    xpack.security.session.idleTimeout: 5m
    xpack.security.session.lifespan: 15m
    
    xpack.encryptedSavedObjects.encryptionKey: "${XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY}"
    xpack.reporting.encryptionKey: "${XPACK_REPORTING_ENCRYPTIONKEY}"
    
    # CORS settings for Google authentication
    server.cors: true
    
    logging.root.level: "debug"