apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.10.0
          ports:
            - containerPort: 5601
          env:
            - name: SERVER_HOST
              value: "0.0.0.0"
            - name: SERVER_SSL_ENABLED
              value: "true"
            - name: SERVER_SSL_CERTIFICATE
              value: "/usr/share/kibana/config/certs/tls.crt"
            - name: SERVER_SSL_KEY
              value: "/usr/share/kibana/config/certs/tls.key"
            - name: SERVER_PUBLICBASEURL
              value: "https://localhost:5601"
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch:9200"
            - name: ELASTICSEARCH_USERNAME
              value: "kibana_system"
            - name: ELASTICSEARCH_PASSWORD
              value: "NewPassword123"
            - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
              value: "none"
            - name: XPACK_SECURITY_ENABLED
              value: "true"
            - name: XPACK_SECURITY_AUTHC_PROVIDERS
              value: '["basic"]'
            - name: XPACK_SECURITY_PUBLIC_PROTOCOL
              value: "https"
            - name: XPACK_SECURITY_LOGINASSISTANCE_ENABLED
              value: "true"
            - name: XPACK_SECURITY_AUTHC_SELECTOR_ENABLED
              value: "true"
            - name: SERVER_HEALTHCHECK_ALLOWANONYMOUS
              value: "true"
            - name: XPACK_SECURITY_COOKIE_SECURE
              value: "true"
            - name: XPACK_SECURITY_SESSION_IDLETIMEOUT
              value: "1h"
            - name: XPACK_SECURITY_SESSION_LIFESPAN
              value: "24h"
            - name: XPACK_CSP_RULES
              value: "script-src 'self' 'unsafe-eval' 'unsafe-inline'; connect-src 'self' http://localhost:5601 https://localhost:5601"
            - name: XPACK_CSP_STRICT
              value: "false"
            - name: LOGGING_ROOT_LEVEL
              value: "debug"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /api/status
              port: 5601
              scheme: HTTPS
              httpHeaders:
                - name: Authorization
                  value: "Basic ZWxhc3RpYzpKQ3FNUmtKZVhPSDhOTFZLQ1ljZg=="
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/status
              port: 5601
              scheme: HTTPS
              httpHeaders:
                - name: Authorization
                  value: "Basic ZWxhc3RpYzpKQ3FNUmtKZVhPSDhOTFZLQ1ljZg=="
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /api/status
              port: 5601
              scheme: HTTPS
              httpHeaders:
                - name: Authorization
                  value: "Basic ZWxhc3RpYzpKQ3FNUmtKZVhPSDhOTFZLQ1ljZg=="
            failureThreshold: 30
            periodSeconds: 10
          volumeMounts:
            - name: kibana-certs
              mountPath: /usr/share/kibana/config/certs
              readOnly: true
      volumes:
        - name: kibana-certs
          secret:
            secretName: kibana-tls
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "purpose"
                    operator: In
                    values:
                      - "elk"
                  - key: "set"
                    operator: In
                    values:
                      - "ss-elk"
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  annotations:
    cloud.google.com/backend-config: '{"default": "kibana-backend-config"}'
spec:
  selector:
    app: kibana
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
  type: ClusterIP