apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: elk-secrets
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/461501268972/secrets/elasticsearch-password/versions/latest"
        path: "elasticsearch-password"
      - resourceName: "projects/461501268972/secrets/kibana-elasticsearch-password/versions/latest"
        path: "kibana-elasticsearch-password"
      - resourceName: "projects/461501268972/secrets/elasticsearch-oidc-client-secret/versions/latest"
        path: "elasticsearch-oidc-client-secret"
      - resourceName: "projects/461501268972/secrets/kibana-oauth-client-id/versions/latest"
        path: "kibana-oauth-client-id"
      - resourceName: "projects/461501268972/secrets/kibana-oauth-client-secret/versions/latest"
        path: "kibana-oauth-client-secret"
      - resourceName: "projects/461501268972/secrets/xpack-security-encryption-key/versions/latest"
        path: "xpack-security-encryption-key"
      - resourceName: "projects/461501268972/secrets/xpack-encrypted-saved-objects-encryption-key/versions/latest"
        path: "xpack-encrypted-saved-objects-encryption-key"
      - resourceName: "projects/461501268972/secrets/xpack-reporting-encryption-key/versions/latest"
        path: "xpack-reporting-encryption-key"
  secretObjects:
    - secretName: elk-credentials
      type: Opaque
      data:
        - objectName: elasticsearch-password
          key: elasticsearch-password
        - objectName: kibana-elasticsearch-password
          key: kibana-elasticsearch-password
        - objectName: elasticsearch-oidc-client-secret
          key: elasticsearch-oidc-client-secret
        - objectName: kibana-oauth-client-id
          key: kibana-oauth-client-id
        - objectName: kibana-oauth-client-secret
          key: kibana-oauth-client-secret
        - objectName: xpack-security-encryption-key
          key: xpack-security-encryption-key
        - objectName: xpack-encrypted-saved-objects-encryption-key
          key: xpack-encrypted-saved-objects-encryption-key
        - objectName: xpack-reporting-encryption-key
          key: xpack-reporting-encryption-key