apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: product-service-secrets
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/461501268972/secrets/product-service-database-password/versions/latest"
        path: "database-password"
      - resourceName: "projects/461501268972/secrets/product-svc-account-credentials/versions/latest"
        path: "product-svc-account-credentials"
  secretObjects:
    - secretName: product-service-secrets
      type: Opaque
      data:
        - objectName: "database-password"
          key: "database-password"