apiVersion: v1
kind: Secret
metadata:
  name: gcp-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "product-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  credentials.json: {{ .Values.gcpCredentials | quote }} 