apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: central-hub-secrets
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/461501268972/secrets/central-hub-oauth2-client-id/versions/latest"
        path: "central-hub-oauth2-client-id"
      - resourceName: "projects/461501268972/secrets/central-hub-oauth2-client-secret/versions/latest"
        path: "central-hub-oauth2-client-secret"
      - resourceName: "projects/461501268972/secrets/central-hub-gcip-api-key/versions/latest"
        path: "central-hub-gcip-api-key"
  secretObjects:
    - secretName: central-hub-secrets
      type: Opaque
      data:
        - objectName: "central-hub-oauth2-client-id"
          key: "oauth2-client-id"
        - objectName: "central-hub-oauth2-client-secret"
          key: "oauth2-client-secret"
        - objectName: "central-hub-gcip-api-key"
          key: "gcip-api-key"