apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: login-service-secrets
  # ... other metadata
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/461501268972/secrets/login-service-user-database-password/versions/latest"
        path: "user-database-password"
      - resourceName: "projects/461501268972/secrets/login-service-otp-database-password/versions/latest"
        path: "otp-database-password"
      - resourceName: "projects/461501268972/secrets/login-service-spring-password/versions/latest"
        path: "mail-password"
  secretObjects:
    - secretName: login-service-secrets
      type: Opaque
      data:
        - objectName: "user-database-password"
          key: "user-database-password"
        - objectName: "otp-database-password"
          key: "otp-database-password"
        - objectName: "mail-password"
          key: "mail-password"